myapp/urls.py
from django.urls import path
from .views import index,create_item,update_item,delete_item,IndexClassView,FoodDetailView,ItemCreateView,ItemUpdateView,ItemDeleteView

#namespacing
app_name='myapp'
urlpatterns = [
    path('',view=IndexClassView.as_view(),name='index'),
    path('item/<int:pk>',view=FoodDetailView.as_view(),name='detail'),
     path('add/',view=ItemCreateView.as_view(),name='item_form'),
     path('update/<int:pk>',view=ItemUpdateView.as_view(), name='update-item'),
     path('delete/<int:pk>',view = ItemDeleteView.as_view(), name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import messages
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('register/',view=views.register,name="register"),
    path('login/',view=auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', view=views.logout_view, name='logout'),
    path('profile/',view = views.profile_view, name="profile"),
] 
 

myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,default =1)
    item_name = models.CharField(max_length=200)
    item_des = models.CharField()
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default='https://www.ikea.com/us/en/images/products/upplaga-plate-white__0714553_pe730123_s5.jpg?f=s')

    #This will be the redirect link of the CreateView or UpdateView class that uses this model
    def get_absolute_url(self):
        return reverse("myapp:detail", kwargs={"pk": self.pk})
    

    def __str__(self):
        return self.item_name

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

myapp/forms.py
from django import forms
from .models import Item
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name',"item_des",'item_price','item_image']
        def form_valid(self,form):
            form.instance.user = self.request.user
            return super().form_valid(form)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

myapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import  DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView

# Create your views here.

@login_required
def index(request):
    item_list = Item.objects.all()
    context = {'items':item_list}
    return render(request,"myapp/index.html",context)


# def detail(request,id):
#     item = Item.objects.get(id=int(id))
#     context = {'item':item}
#     return render(request,"myapp/detail.html",context)



def create_item(request):
    form = ItemForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('myapp:index')
        print("Post request is triggered")
        
    
    context = {'form':form}
    return render(request,'myapp/item-form.html',context) 



def update_item(request,pk):
    item  = Item.objects.get(id=pk)
    if item == None:
        return   redirect('myapp:index')

    if item.user != request.user:
        return HttpResponse("You are not the owner of this item. You cannot edit it.")
    
    itemForm = ItemForm(request.POST or None,instance=item)
    if request.method == 'POST':
        if itemForm.is_valid():
            itemForm.save()
            return   redirect('myapp:index')
    
    context = {'form': itemForm,
                'Type': 'Update'}
    return render(request,'myapp/item-form.html',context)


def delete_item(request,pk):
    item = Item.objects.get(id=pk)
    if request.method =="POST":
      item.delete()
      return redirect('myapp:index')
    return render(request,'myapp/item-delete.html',{})

#   CLASS BASED VIEWS

#Class Based  DeleteView
class ItemDeleteView(DeleteView):
    #this view looks for this template - modelname_confirm_delete.html
    model = Item
    success_url = reverse_lazy("myapp:index")

#cLASS Based Update View
class ItemUpdateView(UpdateView):
    model = Item
    fields = ['item_name',"item_des",'item_price','item_image']
    template_name_suffix =  "_update_form" #Now this view will look for a form that is modelname_update_form.html

     #Will allow only the owner of the item to update it
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

#Class Base Create View
class ItemCreateView(CreateView):
    #Looks for a modelname_form.html in your templates automatically
    model = Item
    fields = ['item_name',"item_des",'item_price','item_image']

#Class Based DetailView
class FoodDetailView(DetailView):
    model = Item
    template_name = 'myapp/detail.html'
    context_object_name = 'item'


#Class Based Index View
class IndexClassView(ListView):
    model = Item
    template_name = 'myapp/index.html'
    context_object_name = 'items'
    

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username} you are now officially registered!')
            return redirect('users:login')
        else:
            print(form.error_messages)
    form = RegisterForm()
    return render(request,'users/register.html',{'form':form})


def logout_view(request):
    logout(request)
    return render(request,"myapp/logout.html",{})

@login_required
def profile_view(request):
    return render(request,'users/profile.html')

myapp/templates/myapp/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>Food App</title>
</head>
<body>
    <nav class="bg-blue-600 text-white " >
      <div  class="flex justify-between px-2 py-4 ">
        <a href="{%url 'myapp:index'%}" class="font-bold text-2xl">FoodApp</a>
        <div class="space-x-3">
         
          <a href="{%url 'users:profile'%}">Welcome {{user.username}}</a>
         {%if user.is_authenticated%}
            <a href={%url "users:logout"%}>Logout</a>
         {%else%}
            <a href={%url "users:login"%}>Login</a>
         {%endif %}
        </div>
      </div>
    </nav>
    {%if messages%}
      {%for message in messages%}
        <div class="bg-green-500 text-green-700">{{message}}</div>
      {%endfor%}
    {%endif%}

    {%block body%}
    {%endblock%}
</body>
</html>

myapp/templates/myapp/detail.html
{%extends 'myapp/base.html'%} {%block body%}

<div class="m-10 flex">
  <div>
    <img class="w-128 rounded-lg" src="{{item.item_image}}" alt="" />
  </div>
  <div class="mx-16 space-y-5">
    <div class="font-bold text-4xl">{{item}}</div>
    <div class="text-green-700 font-bold text-2xl">${{item.item_price}}</div>
    <div>{{item.item_des}}</div>
    <div>
      {%if request.user == item.user%}
      <a
        href="{%url 'myapp:update-item' pk=item.id%}"
        class="bg-yellow-500 px-4 py-2 rounded-md font-bold text-white"
        >Edit</a
      >

      <a
        href="{%url 'myapp:delete_item' pk=item.id%}"
        class="bg-red-500 px-4 py-2 rounded-md font-bold text-white"
        >Delete</a
      >
      {%endif%}
    </div>
  </div>
</div>

{%endblock%}

myapp/templates/myapp/index.html
{%extends 'myapp/base.html'%} {%block body%}

<div>
  {%for item in items%}
  <div class="m-10 flex  w-1/2 mx-auto">
    <div>
      <img class="w-64 rounded-lg" src="{{item.item_image}}" alt="" />
    </div>
    <div class="mx-16">
      <div class="font-bold">{{item.item_name}}</div>
      <div>{{item.item_des}}</div>
      <div>{{item.user}}</div>
      <div class="text-green-700 font-bold">${{item.item_price}}</div>
    </div>
    <div><a class="bg-red-500 font-bold text-white py-2 px-4 rounded-md" href="{%url 'myapp:detail' pk=item.id %}">View Details</a> </div>
  </div>
  {%endfor%}
</div>

{% endblock %}

myapp/templates/myapp/item-delete.html
{%extends 'myapp/base.html'%}

{%block body%}
<form method='POST'> 
    {% csrf_token %}
    <p>Are you sure you want to delete this item?</p>
    <button type="submit">Confirm</button>
</form>
{%endblock%}

myapp/templates/myapp/item-form.html
{%extends 'myapp/base.html'%}

{%block body%}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</form>
</form>

{%endblock%}

 

myapp/templates/myapp/item_confirm_delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this item ?
    <input type="submit" name="" id=""/>
</form>

myapp/templates/myapp/item_form.html
{%extends 'myapp/base.html'%}
{%block body%}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Create Item</h1>
    <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
        {% csrf_token %}
          {%if form.non_field_errors%}
            <div class="bg-red-500 text-white p-2">
                {%for error in form.non_field_errors%}
                    <p>{{error}}</p>
                {%endfor%}
            </div>
        {%endif%}
        {%for field in form%}
            <div>
                <label for="">{{field.label}}</label>
                <div class="border rounded p-2">{{field}}</div>
            </div>
        {%endfor%}
        <button class="bg-blue-500 text-white px-4 py-2 w-full">Create</button>
    </form>
</div>

{% endblock %}

myapp/templates/myapp/item_update_form.html
{%extends 'myapp/base.html'%}
{%block body%}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Update Item</h1>
    <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
        {% csrf_token %}
          {%if form.non_field_errors%}
            <div class="bg-red-500 text-white p-2">
                {%for error in form.non_field_errors%}
                    <p>{{error}}</p>
                {%endfor%}
            </div>
        {%endif%}
        {%for field in form%}
            <div>
                <label for="">{{field.label}}</label>
                <div class="border rounded p-2">{{field}}</div>
            </div>
        {%endfor%}
        <button class="bg-blue-500 text-white px-4 py-2 w-full">Save</button>
    </form>
</div>

{% endblock %}

myapp/templates/myapp/logout.html
<h2>You have been logged out</h2>

users/templates/users/login.html
{% extends "myapp/base.html" %}
{%block body%}
<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Login</h1>
    <form method="POST" class="shadow-lg p-10 space-y-5 ">
        {% csrf_token %}
        {%if form.non_field_errors%}
            <div class="bg-red-500 text-white p-2">
                {%for error in form.non_field_errors%}
                    <p>{{error}}</p>
                {%endfor%}
            </div>
        {%endif%}
        <div>
            <label for="username">Username</label>
            <div class="border-black rounded p-2">{{form.username}}</div>
        </div>
         <div>
            <label for="password">Password</label>
            <div class="border-black rounded p-2">{{form.password}}</div>
        </div>
        <button class="bg-blue-500 px-2 py-2 w-full text-white">Login</button>
    </form>
</div>

{%endblock%}

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" />

users/templates/users/register.html
{%extends 'myapp/base.html'%}
{%block body%}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Sign Up</h1>
    <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
        {% csrf_token %}
          {%if form.non_field_errors%}
            <div class="bg-red-500 text-white p-2">
                {%for error in form.non_field_errors%}
                    <p>{{error}}</p>
                {%endfor%}
            </div>
        {%endif%}
        {%for field in form%}
            <div>
                <label for="">{{field.label}}</label>
                <div class="border rounded p-2">{{field}}</div>
            </div>
        {%endfor%}
        <button class="bg-blue-500 text-white px-4 py-2 w-full">Sign Up</button>
    </form>
</div>

{% endblock %}